### ISSUE TITLE
How to use for classification

### ISSUE THREAD

**Issue by chris-clem** [ISICV/ManTraNet#7]
Hi,

How can I use ManTraNet for fake image classification? I was thinking about using a threshold for the sum of the ManTraNet output, but the output for real images show quite some noise:

![image](https://user-images.githubusercontent.com/36116534/76146197-1b22a080-6091-11ea-850e-fd7d56fb724c.png)

Is there a better way to do it?

**Comment by 22wei22** [comment]
How to use ManTraNet for fake image classification? Do you have ideas?

**Comment by rex-yue-wu** [comment]
I don't know what is your application. But it is clear that the first image is out of the scope that the ManTraNet can handle -- it is already processed by concatenating two images together. 

For fake image classification, I think you need to build additional modules to take the ManTraNet intermediate feature (not the averaged feature, but the deviations) as the input for a classification network.
